[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[profile.default.rpc_endpoints]
mantle = "https://rpc.mantle.xyz"
mantle_testnet = "https://rpc.testnet.mantle.xyz"

[profile.default.etherscan]
mantle = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
use_tabs = false
bracket_spacing = true

[doc]
out = "docs"
